### PR TITLE
Cleaning up remnants of bctools, removed applications

### PR DESCRIPTION
**Pull request by digitalsleuth**
Removed remnants of bctools including bc_report_config, shortcuts to bc_report and gui tools, hashdb, sdhash (both no longer supported, and sdhash has separate support within bulk_extractor).

There will be another PR to follow to fix a support issue with bc_mounter.py and Jammy / Focal and the proper version of Gtk, as well as adding the python files from bulk_extractor (dfxml.py, identify_files.py etc).

Recommend waiting until the second PR comes later this evening before issuing a new release. I'm submitting these separately to ensure that an easy rollback can be accomplished for each section of work.

### CODE REVIEW

**Comment by kamwoods** [comment]
Great. I just got back and was about to note some of these. I'd also just realized that there was no launcher for bulk_extractor command line in the Forensics and Reporting submenu; if not already added back it should go in there.

One other minor note, the outdated BitCurator-Quickstart-v2.2.pdf can be removed from Documentation and Help. Won't replace it for now while I'm still working on the updated doc, which will be still be available on the GitHub wiki.

**Review by kamwoods — APPROVED** [review]

**Comment by digitalsleuth** [comment]
Sounds good. I'll add the bulk_extractor command line in and remove that PDF after the next PR. Additionally, BEViewer is no longer available with bulk_extractor until simsong reworks the project (as indicated at https://github.com/simsong/BEViewer).

**Comment by kamwoods** [comment]
Yeah, I was aware, and have warned other Consortium folks about this as well. We're also still installing openjdk8. Is there anything else that uses that? I recalled it being a holdover *just* for BEViewer, but maybe I'm forgetting something. I know we have at least some users who regularly rip it out, disregard BEViewer, and install a newer Java to support other tools that the need / add to BitCurator.

**Comment by digitalsleuth** [comment]
I kept it in there originally because I wasn't sure if it was required for certain tools which aren't included with BitCurator, but I'll remove it since it's not in there for anything right now. I'll be submitting the next PR in about 30 minutes. Running a couple of last tests first before I submit.

**Pull request merged**
